### ISSUE TITLE
validations in custom dialogs?

### ISSUE THREAD

**Issue by aftercall** [Servoy/svyUtils#12]
I'd like to have some validation methods in custom Dialogs (i.e., you put a passw field and a "repeat pwd" field, the user can' continue if these fields haven't the same value)

**Comment by pruhsert** [comment]
For any component you can set a data change method, e.g.:

textField.setOnDataChangeMethod(onDataChangeMethod)

There you can do your validation directly.

To prevent the dialog from closing on button click until everything is as it should, you can call

button.setCloseDialogOnClick(false)

on the Button object. So you should have everything that's needed for what you want to accomplish.

**Comment by aftercall** [comment]
ok, thanks!

**Comment by aftercall** [comment]
I'm playing with validations... I'd like tu put a label with dynamic text (validation error messages), but I see that the text of a label can't be changed when you call showDialog() method

**Comment by pruhsert** [comment]
A small example. A change password dialog:

```
function dialog() {
	var cd = scopes.svyCustomDialogs.createCustomDialog();
	cd.addPasswordField('Your password');
	cd.addPasswordField('New password');
	cd.addPasswordField('New password (repeat)');
	cd.addLabel('').setName('feedback');
	
	cd.addButton('Cancel');
	cd.addButton('OK')
		.setCloseDialogOnClick(false)
		.setOnActionMethod(onActionBtnOk);
	
	cd.showDialog();
}
```

The cancel button will simply close the dialog, the OK button does not close the dialog, but calls the onActionBtnOK method. That method could look like this:

```
/**
 * @param {JSEvent} event
 * @param {scopes.svyCustomDialogs.CustomDialog} customDialog
 */
function onActionBtnOk(event, customDialog) {
	var dialogResult = customDialog.getResult();
	if (dialogResult[1] != dialogResult[2]) {
		/** @type {scopes.svyCustomDialogs.Label} */
		var label = customDialog.getComponent('feedback');
		label.text = 'New password repeat does not match';
	} else {
		customDialog.closeDialog();
	}
}
```

The method receives a JSEvent and the customDialog object. It checks if newPassword equals newPasswordRepeat and if not, sets the label text of label "feedback". If all is OK, it simply closes the dialog.

I hope that helps to get you started.

**Comment by aftercall** [comment]
Thanks!

I prefer to use one function (instead of using another function for setOnActionMethod), so the method looks like:

```
cd.showDialog();

if (cd.buttonClickedText == 'OK') {
    var dialogResult = cd.getResult();
	if (dialogResult[1] != dialogResult[2]) {
		/** @type {scopes.svyCustomDialogs.Label} */
		var label = cd.getComponent('feedback');
		label.text = 'New password repeat does not match';
	} else {
		cd.closeDialog();
	}
} else {
    return;
}
```
The problem I found is when the text is long, I can't increase the with of the dialog...

**Comment by pruhsert** [comment]
you could set the label width when you create the dialog...
