### ISSUE TITLE
Please add 'showSelectDialog' to dialogs

### ISSUE THREAD

**Issue by servoyguru** [Servoy/svyUtils#17]
Please can you add showSelectDialog as it does seem to work in NG client, but isn't in your module.
If there might be a way to add something like a showValueListDialog that displays a value list define in solution and returns whatever the value list returns, so it's easy to get someone to choose a display value (with possible extra details), but returns an ID (real value) [this is actually what I want, but it's probably trivial to update to quickly add showSelectDialog.
Thanks
Rafi

**Comment by pruhsert** [comment]
Added a method showSelectDialog(title, message, valueListNameOrDisplayValues, [realValues])
