### ISSUE TITLE
Issue with application.getServerURL() and WarName in Deep Link

### ISSUE THREAD

**Issue by biannetta** [Servoy/svyUtils#18]
If the application is not deployed at the ROOT context of the Tomcat server, `application.getServerURL()` returns `YOURHOST/deployedWar`. Because of this, when a `warName` is passed into this function, the deep link returned will be `YOURHOST/deployedWar/warName` which is invalid.

https://github.com/Servoy/svyUtils/blob/dd4f7177a9c59196069267611204c04b4ad1a2d2/svyUtils/svySystem.js#L429

**Comment by paronne** [comment]
warName param has been removed from method getSolutionDeepLinkNGClient
