### ISSUE TITLE
Unable to run excel export in NG Client

### ISSUE THREAD

**Issue by josdebruijn** [Servoy/svyUtils#20]
I am trying to do an Excel export on Svy 8.2.2, I have followed all the steps in the Wiki:
- latest Jasper plugin (6.4.1)
- added poi's
- modified jasper jnlp file (not sure it is necessary as I run NG client, but done anyway, I have even tested with the sample jnlp file on the wiki)
- the latest release of svyUtils (1.3.1) and svyUtilsExcel (1.3.0). And also tested against the master branch of svyUtils

But when I run the export in my developer I get errors (see [errors.txt](https://github.com/Servoy/svyUtils/files/1719383/errors.txt))

The strangest thing is that I have Svy 8.2.1 deployed on a test server without jasper plugin or the extra poi's and there the excel export is working without problems!

My sample solution: 
[sample_export.zip](https://github.com/Servoy/svyUtils/files/1719385/sample_export.zip)

**Comment by jeffreyvdhondel** [comment]
It's not only ngclient i have the same issue with webclient.
So i should be a combination between 8.2.2 and svyExcelUtils.

**Comment by josdebruijn** [comment]
@jeffreyvdhondel It seems that 8.2.2 broke the excel utils. Probably by changing some jar version. I have heard it is already fixed in svyExcelUtils, but this fix is not yet released. But when you checkout the svy82 branch you have the fixed files. 
I have tested this and it is working again for me.

**Comment by pruhsert** [comment]
This is indeed an issue that arose with 8.2.2. We will release an update to svyUtils soon. It is already fixed in the svy82x branch.
