### ISSUE TITLE
Servoy 8.4+ has warnings for svyCustomDialog

### ISSUE THREAD

**Issue by tuanway** [Servoy/svyUtils#25]
![image001](https://user-images.githubusercontent.com/7150474/55343185-36902f00-5470-11e9-8e3d-4d764ce557e4.png)
![image002](https://user-images.githubusercontent.com/7150474/55343190-3859f280-5470-11e9-8a41-4e7cb3a62f53.png)

**Comment by pruhsert** [comment]
that should be fixed
