### ISSUE TITLE
Security Exception Error

### ISSUE THREAD

**Issue by wvitpr** [Servoy/svyUtils#31]
Im getting 
```
Description	Resource	Path	Location	Type
SecurityException: Signers of 'org.apache.poi.POIXMLDocument' do not match signers of other classes in package	svyExcelUtils.js	/svyUtils$Excel	Unknown	JavaScript Problem
```
Im not sure what I have done wrong here, I followed the instructions. 
Servoy Version
Version: 2020.3.0.3562
Jasper Plugin
v.6.12.2_2020.03

I download poi.zip extracted it to dir poi in 
C:\Servoy_2019_12\application_server\plugins\poi

Contents Below.
![image](https://user-images.githubusercontent.com/83966/83241836-c3528c00-a1de-11ea-970f-91fa89a9fd20.png)

Changed servoy_jasperreports.jar.jnlp to below
![image](https://user-images.githubusercontent.com/83966/83242154-4378f180-a1df-11ea-9e30-f1199c9d1e96.png)

**Comment by pruhsert** [comment]
That sounds as if you had the wrong POI package. The error message complains about different code signing certificates. Are you sure you are using the POI package from

https://github.com/Servoy/svyUtils/wiki/svyExcelUtils/plugins_2020_03/poi.zip

(so the one matching 2020.03, meaning it is signed with the code certificate of 2020.03)

**Comment by wvitpr** [comment]
Hi Patrick, 
This is now resolved, we moved the extension details from the top .jnlp file and inserted it at the end. Error has now gone.. :-), thanks for the quick reply though..
