### ISSUE TITLE
Missing JSDoc tag

### ISSUE THREAD

**Issue by SteveHawes** [Servoy/svyUtils#34]
The function getWorkingDays in svyDateUtils is missing the JSDoc tag for its return value. It should be:

`@return {Array<Date>}`

The declaration of the variable result should also be tagged:

`/** @type {Array<Date>} */`

Currently if you use something like:

`var workingDays = scopes.svyDateUtils.getWorkingDays(startDate, endDate, [0, 6]).length - 1;`

you will get a warning marker on the length property.

**Comment by pruhsert** [comment]
Will be fixed with next release.
