### ISSUE TITLE
Custom Dialogs What component type are using? the servoy deprecate or bootstrap component

### ISSUE THREAD

**Issue by juanetec** [Servoy/svyUtils#38]
Hi,
I am using Custom Dialogs for long. The component that it use, like TextField, are this components the servoy deprecate?
I am now working with NG. 
Could I change them to the NG comoponent? 
if yes how?
If not will be a problem with the NG2?

Un Saludo

Juan Ramírez

**Comment by seanthomasdevlin** [comment]
Hola Juan,

Thanks for using the SvyUtils custom dialog feature. I believe there should be no problem. The "classic" components "text-field" etc. are still supported. What will not be compatible are classic ListView/TableView forms. They should be replaced with modern components. But I don't believe these are used in the custom dialogs feature.

Hope this helps.

Best,
Sean

**Comment by juanetec** [comment]
OK thanks for your quick replay.

Un Saludo

Juan Ramírez
