### ISSUE TITLE
svyExcelUtils Reading excel files in developer vs server (in server does not work)

### ISSUE THREAD

**Issue by juanetec** [Servoy/svyUtils#40]
Hi,
using that module and if I read an excell file it work perfect in developer but went I try to do in production it read the file detect the lines but If i try to read the data are empty, if I try to read a row it return the data but no values.
If I try to read a row  data.getRowAsArray(1) it return [,,],
I have used the example from the wiki.
I am using the last plugin version(1.6.1) and the last jasperReport version (6.17.0_1) and the last servoy version(2021.12.2).
Using another process like exporting files works fine.
Below is the code I use to test it:

`/**
 * @properties={typeid:24,uuid:"A6DD7C0D-59D6-4EEE-A9A7-4C72AA55A8C0"}
 */
function base_test_plugin_NG_svy_excell_read(){
	//-Elegir fichero
	 plugins.file.showFileOpenDialog(1,null,false,["XLS","xls","XLSX","xlsx", "SXLSX","sxlsx"],base_test_plugin_NG_svy_excell_readCallback);
}

/**
 * @param {Array<plugins.file.JSFile>} _jsfileArray
 * @return {Boolean}
 * @properties={typeid:24,uuid:"45FED541-940C-4CE9-A81A-9139F29885DB"}
 */
function base_test_plugin_NG_svy_excell_readCallback(_jsfileArray){
	var /** @type {plugins.file.JSFile} */ _jsFile
	if (!_jsfileArray || !_jsfileArray.length){
		scopes.utl_dialog.utl_dialog_error(i18n.getI18NMessage('set.selec_fichero'));
		return false;
	}
	_jsFile = _jsfileArray[0];
	if (!_jsFile){
		scopes.utl_dialog.utl_dialog_error('No ha seleccionado ningún fichero');
		return false;
	}
	//read workbook
	var workbook = scopes.svyExcelUtils.getWorkbook(_jsFile.getBytes());
	//get sheet containing the data
	var sheet = workbook.getSheet('Test');
	//get the data from rows 1 to 5, column 1 and 2
	var data = sheet.getSheetData(true, 1, 5, 1, 2);
	//output result
	application.output('base_test_plugin_svy_excell_read '+data.getAsText('\t', '\n', '', true));
	if (data.getValue(4,1)!=10){
		application.output('base_test_plugin_svy_excell_read (data.getValue(4,1)!=10) '+data.getValue(4,1),LOGGINGLEVEL.ERROR);
		scopes.utl_dialog.utl_dialog_error('svy_excell_read '+data.getValue(4,1));
		return false;
	}
	scopes.utl_dialog.utl_dialog_success('svy_excell_read: <br>'+ data.getAsText('\t', '<br>', '', true));
	return true;
}`

Un Saludo

Juan Ramírez

**Comment by pruhsert** [comment]
What do you mean by "in production"? In a smart client that runs of a server? An NG Client? A headless client?

Without closely looking at the code sample, it is very likely a library issue. On the server, you have some version conflict or a missing library or whatever. Hard to say from here what's wrong.

**Comment by juanetec** [comment]
Sorry Patrick, In NG Client.
I try in Smart Client and it works, non In NG Client.
Could be a version conflict or a missing library if that works in Smart Client?
I don't see any Error on servoy server Error.

Un saludo
Juan Ramírez

**Comment by juanetec** [comment]
Hi,
could be a conflict with the file poi-4.1.1.jar (from jasperReport) and jakarta-poi.jar (from excelxport) or with itext-2.1.7.js8.jar  (from jasperReport) and itext-2.1.7.jar (pdf_output).

Un Saludo
Juan Ramírez
