### ISSUE TITLE
svyExcelUtils.createWorkBookFromDataSet gives an error after upgrade

### ISSUE THREAD

**Issue by og1** [Servoy/svyUtils#44]
I make use of the svyExcelUtils.createWorkBookFromDataSet. After upgrading to Servoy 2023-06 and using the latest packages (svyUtil$Excel 2023.03.0) exporting to Excel with this method now produces a Server Error which is show in big red letters in the frontend. As a workaround I reverted back to 2022.3.1. That still works.

**Comment by seanthomasdevlin** [comment]
Hi og1, can you share what the error is?

Best,
Sean

**Comment by og1** [comment]
Hi Sean, sorry, I reverted to a previous version and have not been here for a while. I just did a new attempt and I get an Internal Server Error in the browser. The console and log show this execption: 

ERROR org.sablo.eventthread.EventDispatcher - [dispatch()] Exception happened in dispatch() java.lang.NoClassDefFoundError: org/apache/xmlbeans/XmlException

**Comment by pruhsert** [comment]
Did you also download the latest POI libraries matching your Servoy version?

Please have a look here https://github.com/Servoy/svyUtils/wiki/ExcelUtils#installation, make sure you have the matching POI package and try again.

**Comment by og1** [comment]
Hi Patrick, that did the trick. I only updated the plugin through the Package Manager. Thanks for your suggestion! Does this mean that I have to manually check the release notes for each plugin after every Servoy release? I did not see this in the Servoy release notes and it worked in the release before that.

**Comment by og1** [comment]
I also have an issue with the dialogs plugin, the buttons of the showQuestionDialog are sticking out of the bottom of the dialog window. Do you have a suggestion for that as well?
