### ISSUE TITLE
Incorrect dates in batch processor using TODAY_START and TODAY_END

### ISSUE THREAD

**Issue by og1** [Servoy/svyUtils#6]
svyDateUtils initializes the constants TODAY_START and TODAY_END by using an anonymous function for initTodayVars. This causes errors/bugs in any process that runs over midnight. The next day and all days after that the constants will have the same date until the process is restarted.

**Comment by pruhsert** [comment]
These variables are only meant to be used in relations. To be used as such, we can't make them methods. The only option to fix this would be to schedule a job that will reset them.

**Comment by og1** [comment]
Hmm. In a relation the same bug will occur and be rather difficult to trace back to this particular issue. It would be nice if these constants were added to Servoy Java code with a proper getter. Anyway, thanks for your reply Patrick.

**Comment by pruhsert** [comment]
I think we should add a scheduler that resets these. What's wrong with that? It will simply run once a day.

**Comment by og1** [comment]
If that's easy to do then it could avoid some nasty trouble ;-). However, it seems like it would be hard to get it to switch at exactly midnight or else it could still fail, especially if other jobs are running at the same time.

**Comment by pruhsert** [comment]
I think it will *work* in such a way that it tries to get it right at midnight. Possibly, it's done later. But maybe better than never.

Getters for scope variables would be nice indeed.

**Comment by pruhsert** [comment]
I added a schedule now to reset these

**Comment by og1** [comment]
Great. Thanks, Patrick!

Kind regards,

Omar van Galen             


06-2 12345 86
omar@intrasoft.nl <mailto:omar@intrasoft.nl>
