### ISSUE TITLE
Servoy 7 Version?

### ISSUE THREAD

**Issue by clickguy** [Servoy/svyUtils#8]
Is there a Servoy 7 version available?

We have not yet updated our servers to 8.0x and I would still like to be able to integrate it into our solution(s).

**Comment by seanthomasdevlin** [comment]
Hi ClickGuy, yes it works with Servoy 7
Please try the [binaries](https://github.com/Servoy/svyUtils/releases/tag/v1.2.0) that were recently attached in the 1.2.0 release which are compiled for 7.x compliance or download repository or run from source

**Comment by clickguy** [comment]
Thanks very much Sean! You're AWESOME! :)
