### ISSUE TITLE
Servoy 7 Support In 1.2.0 - Not So Much

### ISSUE THREAD

**Issue by clickguy** [Servoy/svyUtils#9]
Hey Guys,

I downloaded the 1.2.0 binary and tried to import all the solutions with "$" in the title into Developer 7.4.6.

No love. Got this message on import:

> Could not import solution: The solution was exported with a newer version of Servoy than you are currently running. Upgrade to at least Servoy 8.1.2 -build 3031 to import this solution.

**Comment by seanthomasdevlin** [comment]
Hi Bob,

It appears that even if the fileVersion is set in the rootMetadata.obj file, the export still takes the version from servoy developer.

I re-exported the svyUtilsXXX files and attached to this release.
The crypto and dialogs examples solutions will remain compatible only with 8.1+

**Comment by clickguy** [comment]
Hey Sean,

Thanks so much for all your extra efforts. Sorry for being a pain!
